let
    // -----------------------------
    // Parameters (create in Manage Parameters as Text)
    // -----------------------------
    // pSpecUrl: Raw GitHub URL to your JSON config
    // pSharePointSiteRoot: e.g., "https://<tenant>.sharepoint.com"
    // pSharePointFolderPath: e.g., "https://neogencorp-my.sharepoint.com/:x:/r/personal/jgaley_neogen_com/Documents/Documents/NA_TriTable_Ref.xlsx?d=w028ff9f42461401397f03ec04a0c8522&csf=1&web=1&e=d6Z3Jo"
    // pWorkbookName: e.g., "NA_TriTable_Ref.xlsx"

    // ---- Config source ----
    Spec = Json.Document(Web.Contents(pSpecUrl)),

    // ---- Excel source (SharePoint/OneDrive) ----
    Files      = SharePoint.Files(pSharePointSiteRoot, [ApiVersion = 15]),
    Filtered   = Table.SelectRows(
                    Files,
                    each [Folder Path] = pSharePointFolderPath and [Name] = pWorkbookName
                 ),
    BookBinary = if Table.RowCount(Filtered) = 0
                 then error "Workbook not found at: " & pSharePointFolderPath & pWorkbookName
                 else Filtered{0}[Content],
    BookAll    = Excel.Workbook(BookBinary, null, true)

    // ---- (keep the rest of your script unchanged: ResolveToken, GetBlock, TrimClean, etc.) ----

in

    BookAll
