let
    // -----------------------------
    // Parameters (create in Manage Parameters as Text)
    // -----------------------------
    // pSpecUrl: Raw GitHub URL to your JSON config
    // pSharePointSiteRoot:https://neogencorp-my.sharepoint.com
    // pSharePointFolderPath:/personal/jgaley_neogen_com/Documents/Documents/
    // pWorkbookName:NA_TriTable_Ref.xlsx

    // ---- Config source ----
    Spec = Json.Document(Web.Contents(pSpecUrl)),

    // ---- Excel source (SharePoint/OneDrive) ----
    Files      = SharePoint.Files(pSharePointSiteRoot, [ApiVersion = 15]),
    Filtered   = Table.SelectRows(
                    Files,
                    each [Folder Path] = pSharePointFolderPath and [Name] = pWorkbookName
                 ),
    BookBinary = if Table.RowCount(Filtered) = 0
                 then error "Workbook not found at: " & pSharePointFolderPath & pWorkbookName
                 else Filtered{0}[Content],
    BookAll    = Excel.Workbook(BookBinary, null, true)

    // ---- (keep the rest of your script unchanged: ResolveToken, GetBlock, TrimClean, etc.) ----

in

    BookAll


